// VibeWiredHarness MCP Server - Dual Mode
// MCP agent coordination: 100% unchanged for Claude Code / all agents
// Browser observer: GET / returns live Swagger-like dashboard
const http=require("http"),fs=require("fs"),path=require("path");
const PORT=process.env.MCP_PORT||3100,ROOT=path.join(__dirname,"..");
const CH={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type,Accept"};
function ags(){try{return f.readdirSync(path.join(ROOT,"agents")).filter(x=>x.endsWith(".md")).map(x=>{const n=x.replace(".md",""),t=f.readFileSync(path.join(ROOT,"agents",x),"utf8"),m=t.match(/description[^\n]*:\s*["\x27]?(["\x27\n]{3,})/m),h=t.match(/^#\s+(.+)/m);return{n,d:(m?m[1]:h?h[1]:"AI agent").trim().slice(0,110)};});}catch(e){return[];}}
function cs(){try{return f.readdirSync(path.join(ROOT,"commands")).filter(x=>x.endsWith(".md")).map(x=>x.replace(".md",""));}catch(e){return[];}}
function J(res,o){res.writeHead(200,Object.assign({},CH,{"Content-Type":"application/json"}));res.end(JSON.stringify(o,null,2));}
const srv=http.createServer((req,res)=>{
const A=ags(),C=cs(),u=req.url.split("?")[0],acc=req.headers["accept"]||"";
if(req.method==="OPTIONS"){res.writeHead(204,CH);res.end();return;}
if(u==="/ping"||u==="/health")return J(res,{status:"ok",agents:A.length,commands:C.length,port:PORT,layer:"1-mcp",dashboard:"http://localhost:"+PORT});
if(u==="/tools/list")return J(res,{tools:A.map(a=>({name:a.n,description:a.d}))});
if(u==="/resources/list")return J(res,{resources:["agents/","services/","commands/","hooks/","rules/","skills/"]});
if(u==="/prompts/list")return J(res,{prompts:C.map(n=>({name:n,invoke:"/"+n}))});
if(u.startsWith("/agent/")){const ag=A.find(a=>a.n===u.slice(7));if(ag)return J(res,ag);res.writeHead(404,CH);res.end(JSON.stringify({error:"not found"}));return;}
if(u==="/tools/call"&&req.method==="POST"){let b="";req.on("data",c=>b+=c);req.on("end",()=>{try{const d=JSON.parse(b||"{}}"),ag=A.find(a=>a.n===d.tool);if(!ag){res.writeHead(404,CH);res.end(JSON.stringify({error:"not found: "+(d.tool||"?")}));return;}J(res,{agent:d.tool,status:"ready",description:ag.d,message:"Agent "+d.tool+" wired on MCP:"+PORT+". Connect Claude Code for real AI calls.",params:d.params});}catch(e){res.writeHead(400,CH);res.end(JSON.stringify({error:e.message}));}});return;}
// Browser dashboard - only served to browsers (Accept: text/html)
if((u==="/"||u==="")&&(acc.includes("text/html")||acc.includes("*/*")||acc==="")){
const L="\x3c",G="\x3e";
const ar=A.map(a=>L+"tr"+G+L+"td"+G+L+"code"+G+a.n+L+"/code"+G+L+"/td"+G+L+"td style=\"color:#8b949e;font-size:12px\""+G+a.d+L+"/td"+G+L+"td"+G+L+"button style=\"background:#238636;color:#fff;border:none;padding:4px 8px;border-radius:4px;cursor:pointer;margin:2px\" onclick=\"ping("+JSON.stringify(a.n)+")\""+G+"Ping"+L+"/button"+G+" "+L+"button style=\"background:#1f6feb;color:#fff;border:none;padding:4px 8px;border-radius:4px;cursor:pointer\" onclick=\"call2("+JSON.stringify(a.n)+")\""+G+"Call"+L+"/button"+G+L+"/td"+G+L+"td id=s"+a.n.replace(/\\W/g,"_")+" style=\"width:40px\""+G+L+"/td"+G+L+"/tr"+G).join("");
const nm=JSON.stringify(A.map(a=>a.n));
const cr=C.slice(0,30).map(n=>L+"tr"+G+L+"td"+G+L+"code"+G+"/"+n+L+"/code"+G+L+"/td"+G+L+"/tr"+G).join("");
const css="body{font-family:monospace;background:#0d1117;color:#c9d1d9;padding:20px;margin:0}h1{color:#58a6ff;border-bottom:2px solid #30363d;padding-bottom:8px;margin-bottom:8px}h2{color:#79c0ff;margin:16px 0 8px}p{color:#8b949e;font-size:13px;line-height:1.6;margin-bottom:6px}table{width:100%;border-collapse:collapse;font-size:13px;margin-bottom:8px}th{background:#161b22;color:#8b949e;padding:6px 9px;text-align:left;border:1px solid #30363d}td{padding:5px 9px;border:1px solid #21262d;vertical-align:middle}tr:hover td{background:#161b22}code{background:#161b22;padding:1px 5px;border-radius:4px;color:#79c0ff}.ep{display:flex;flex-wrap:wrap;gap:8px;margin:10px 0}.ep div{background:#161b22;border:1px solid #30363d;border-radius:6px;padding:10px;min-width:190px;flex:1}.ep p{color:#8b949e;font-size:12px;margin:4px 0 8px}.ep button{width:100%;border:none;padding:5px;border-radius:4px;cursor:pointer;font-size:12px;font-family:monospace}#log{background:#010409;border:1px solid #30363d;border-radius:4px;padding:8px;height:130px;overflow-y:auto;font-size:12px;margin-top:6px}#pr{display:none;align-items:center;gap:10px;margin-bottom:10px}#pbar{flex:1;background:#21262d;border-radius:4px;height:7px;overflow:hidden}#pb{background:#58a6ff;height:7px;width:0%;transition:width .2s}a{color:#58a6ff}";
const jsb64="Y29uc3QgTD1kb2N1bWVudC5nZXRFbGVtZW50QnlJZCgibG9nIiksQUxMPU5NO2xldCBkb25lPTA7ZnVuY3Rpb24gbG9nKG0sYyl7Y29uc3QgZT1kb2N1bWVudC5jcmVhdGVFbGVtZW50KCJkaXYiKTtlLnN0eWxlLmNvbG9yPWN8fCIjM2ZiOTUwIjtlLnRleHRDb250ZW50PSJbIituZXcgRGF0ZSgpLnRvTG9jYWxlVGltZVN0cmluZygpKyJdICIrbTtMLmluc2VydEJlZm9yZShlLEwuZmlyc3RDaGlsZCk7fWFzeW5jIGZ1bmN0aW9uIGdvKHUpe2xvZygiR0VUICIrdSwiIzU4YTZmZiIpO3RyeXtjb25zdCByPWF3YWl0IGZldGNoKHUpO2xvZyhKU09OLnN0cmluZ2lmeShhd2FpdCByLmpzb24oKSkuc2xpY2UoMCwzMDApKTt9Y2F0Y2goZSl7bG9nKGUubWVzc2FnZSwiI2Y4NTE0OSIpO319YXN5bmMgZnVuY3Rpb24gdHJ5Q2FsbCgpe2NvbnN0IHQ9cHJvbXB0KCJBZ2VudDoiLCJjb2RlLXJldmlld2VyIik7aWYoIXQpcmV0dXJuO2NvbnN0IHE9cHJvbXB0KCJUYXNrOiIsIkRlc2NyaWJlIHlvdXJzZWxmLiIpO2lmKCFxKXJldHVybjt0cnl7Y29uc3Qgcj1hd2FpdCBmZXRjaCgiL3Rvb2xzL2NhbGwiLHttZXRob2Q6IlBPU1QiLGhlYWRlcnM6eyJDb250ZW50LVR5cGUiOiJhcHBsaWNhdGlvbi9qc29uIn0sYm9keTpKU09OLnN0cmluZ2lmeSh7dG9vbDp0LHBhcmFtczp7dGFzazpxfX0pfSk7bG9nKEpTT04uc3RyaW5naWZ5KGF3YWl0IHIuanNvbigpKS5zbGljZSgwLDMwMCkpO31jYXRjaChlKXtsb2coZS5tZXNzYWdlLCIjZjg1MTQ5Iik7fX1hc3luYyBmdW5jdGlvbiBwaW5nKG4pe2NvbnN0IGVsPWRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJzIituLnJlcGxhY2UoL1teYS16MC05XS9nLCJfIikpO2lmKGVsKWVsLnRleHRDb250ZW50PSIuLi4iO3RyeXthd2FpdCBmZXRjaCgiL3Rvb2xzL2NhbGwiLHttZXRob2Q6IlBPU1QiLGhlYWRlcnM6eyJDb250ZW50LVR5cGUiOiJhcHBsaWNhdGlvbi9qc29uIn0sYm9keTpKU09OLnN0cmluZ2lmeSh7dG9vbDpuLHBhcmFtczp7dGFzazoicGluZyJ9fSl9KTtpZihlbCl7ZWwudGV4dENvbnRlbnQ9Ik9LIjtlbC5zdHlsZS5jb2xvcj0iIzNmYjk1MCI7fWxvZyhuKyI6IHJlYWR5Iik7fWNhdGNoKGUpe2lmKGVsKXtlbC50ZXh0Q29udGVudD0iRVJSIjtlbC5zdHlsZS5jb2xvcj0iI2Y4NTE0OSI7fX19YXN5bmMgZnVuY3Rpb24gY2FsbDIobil7Y29uc3QgcT1wcm9tcHQoIlRhc2s6IiwiRGVzY3JpYmUgeW91cnNlbGYuIik7aWYoIXEpcmV0dXJuO3RyeXtjb25zdCByPWF3YWl0IGZldGNoKCIvdG9vbHMvY2FsbCIse21ldGhvZDoiUE9TVCIsaGVhZGVyczp7IkNvbnRlbnQtVHlwZSI6ImFwcGxpY2F0aW9uL2pzb24ifSxib2R5OkpTT04uc3RyaW5naWZ5KHt0b29sOm4scGFyYW1zOnt0YXNrOnF9fSl9KTtjb25zdCBqPWF3YWl0IHIuanNvbigpO2xvZyhuKyI6ICIrKGoubWVzc2FnZXx8SlNPTi5zdHJpbmdpZnkoaikpLnNsaWNlKDAsMjAwKSk7fWNhdGNoKGUpe2xvZyhlLm1lc3NhZ2UsIiNmODUxNDkiKTt9fWFzeW5jIGZ1bmN0aW9uIHBpbmdBbGwoKXtkb25lPTA7ZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoInByIikuc3R5bGUuZGlzcGxheT0iZmxleCI7bG9nKCJQaW5naW5nIGFsbCAiK0FMTC5sZW5ndGgrIiBhZ2VudHMuLi4iLCIjNThhNmZmIik7Zm9yKGNvbnN0IG4gb2YgQUxMKXthd2FpdCBwaW5nKG4pO2RvbmUrKztkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGIiKS5zdHlsZS53aWR0aD1NYXRoLnJvdW5kKGRvbmUvQUxMLmxlbmd0aCoxMDApKyIlIjtkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgicGMiKS50ZXh0Q29udGVudD1kb25lKyIvIitBTEwubGVuZ3RoO2F3YWl0IG5ldyBQcm9taXNlKHI9PnNldFRpbWVvdXQociwzMCkpO31sb2coIkRvbmU6ICIrQUxMLmxlbmd0aCsiIGFnZW50cyBwaW5nZWQuIik7fQ==";
const js=Buffer.from(jsb64,"base64").toString().replace("NM",nm);
const htm="\\x3c"+"!DOCTYPE html"+"\\x3e"+"\\x3c"+"html"+"\\x3e"+"\\x3c"+"head"+"\\x3e"+"\\x3c"+"meta charset=utf-8"+"\\x3e"+"\\x3c"+"title"+"\\x3e"+"VWH MCP Observer :"+PORT+"\\x3c"+"/title"+"\\x3e"+"\\x3c"+"style"+"\\x3e"+css+"\\x3c"+"/style"+"\\x3e"+"\\x3c"+"/head"+"\\x3e";
const body="\\x3cbody\\x3e\\x3ch1\\x3eVWH MCP Observer\\x3c/h1\\x3e\\x3cp\\x3eLayer 1: "+(A.length)+" agents on :"+(PORT)+" | MAMGA :7788 | browser-harness | obsidian-wiki\\x3c/p\\x3e";
const tbl=L+"h2"+G+"Wired Agents ("+A.length+")"+L+"/h2"+G+L+"div style="display:flex;gap:10px;align-items:center;margin-bottom:10px""+G+L+"button style="background:#8957e5;color:#fff;border:none;padding:7px 20px;border-radius:4px;cursor:pointer;font-weight:700" onclick="pingAll()""+G+"Ping All"+L+"/button"+G+L+"div id=pr style="display:none;align-items:center;gap:10px;flex:1""+G+L+"div id=pbar style="flex:1;background:#21262d;border-radius:4px;height:7px;overflow:hidden""+G+L+"div id=pb style="background:#58a6ff;height:7px;width:0%""+G+L+"/div"+G+L+"/div"+G+L+"span id=pc style="color:#8b949e;font-size:12px""+G+L+"/span"+G+L+"/div"+G+L+"/div"+G+L+"table"+G+L+"tr"+G+L+"th"+G+"Agent"+L+"/th"+G+L+"th"+G+"Description"+L+"/th"+G+L+"th"+G+"Actions"+L+"/th"+G+L+"th"+G+"Status"+L+"/th"+G+L+"/tr"+G+ar+L+"/table"+G+L+"h2"+G+"Commands"+L+"/h2"+G+L+"table"+G+L+"tr"+G+L+"th"+G+"Command"+L+"/th"+G+L+"/tr"+G+cr+L+"/table"+G+L+"h2"+G+"Log"+L+"/h2"+G+L+"div id=log"+G+"Ready on :"+PORT+". MCP coordination unchanged."+L+"/div"+G;
const full=htm+body+eps+tbl+L+"script"+G+js+L+"/script"+G+L+"/body"+G+L+"/html"+G;
res.writeHead(200,Object.assign({},CH,{"Content-Type":"text/html;charset=utf-8"}));res.end(full);
return;
}
res.writeHead(404,CH);res.end(JSON.stringify({error:"Not found",endpoints:["/","/ping","/tools/list","/tools/call","/resources/list","/prompts/list","/agent/:name"]}));
});
srv.listen(PORT,"0.0.0.0",()=>{
console.log("VWH MCP Observer: http://localhost:"+PORT);
console.log("API: /ping /tools/list /tools/call /resources/list /prompts/list /agent/:name");
});
